# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  Namkuweb:
    image: trchuy24/namkuweb
    restart: always
    container_name: abc
    ports: 
      - "80:80"